### ISSUE TITLE
404 on uptime and status images

### ISSUE THREAD

**Issue by wrac4242** [countr/docs#14]
The images for the bots uptime and status are not showing
![image](https://user-images.githubusercontent.com/42539664/126191794-93d6c7c8-57e0-4dcd-a568-29f8c2c28eb8.png)

The console shows this as a 404 on the hosting side 
![image](https://user-images.githubusercontent.com/42539664/126191859-262fbbcd-0b18-49bc-89a2-b31d244720c1.png)

**Comment by wrac4242** [comment]
hi, i just want to see if this has been seen?

**Comment by promise** [comment]
I've asked the botlist.space site admins, uptime widgets will not be coming back. Might make something private for this instead though.

**Comment by promise** [comment]
had some caching issues etc. but should all be fixed now. works perfectly in incognito mode, might take 30 minutes to update elsewhere
![image](https://user-images.githubusercontent.com/10573728/126878507-269651e0-b54d-44bc-ac8a-4b47f43f0541.png)
